FROM ubuntu:20.04
LABEL maintainer="Mo1cibo"

# Initial update
RUN apt update && apt install -y --no-install-recommends build-essential

# Other packages
RUN apt install -y --no-install-recommends \
    vim
